### ISSUE TITLE
JSFiddle example link is wrong

### ISSUE THREAD

**Issue by sotojuan** [developit/precharts#2]
It links to this repo!

**Comment by developit** [comment]
lol - its empty, I don't have a fiddle up anywhere. This lib has a ton of dependencies (lodash, core-js, etc) that are annoying to fake out via unpkg.  Maybe browserify-cdn...

Ah! I know - I can use webpackbin!

[edit] crap I took down webpackbin

**Comment by developit** [comment]
Fixed!
