### ISSUE TITLE
Publish a new version to npm

### ISSUE THREAD

**Issue by danielbayerlein** [developit/precharts#30]
Can you please publish a new version?
Alternatively, you can add me as a contributor at npm.

**Comment by developit** [comment]
Added you to the package! 👍 

Not sure if you saw it yet, but this is using a little release script. Feel free to change it to use `np` or `release` or something (I'd be curious to see how they work!), otherwise the process is:

```sh
edit package.json   # change the version and save

# don't commit the version bump!

npm run release   # does: test -> commit -> tag -> push -> publish
```

**Comment by danielbayerlein** [comment]
Thank you! 👍

**Comment by danielbayerlein** [comment]
Done (95b6087) `v1.3.0` is published  🎉
